### ISSUE TITLE
Setup instructions?

### ISSUE THREAD

**Issue by Unzor** [raxod502/riju#95]

**Comment by raxod502** [comment]
Would you please elaborate? If you are trying to deploy your own instance of Riju, there is extensive documentation at https://github.com/raxod502/riju/blob/master/doc/selfhosting.md.

**Comment by raxod502** [comment]
This thread is being closed automatically by [Tidier](https://github.com/raxod502/tidier) because it is labeled with "waiting on response" and has not seen any activity for 90 days. But don't worry—if you have any information that might advance the discussion, leave a comment and I will be happy to reopen the thread :)
